title: PSY-WORLD 
email: 6howcome9@gmail.com
description: Welcome to PSY-WORLD
baseurl: "" #
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# style
sass:
  sass_dir: _sass
  style: compressed