title: PSY-WORLD
author: PSY 
email: 6howcome9@gmail.com
description: Welcome to PSY-WORLD

baseurl: "" #
url: ""
permalink: /:categories/:title

# github
github_username:  6howcome9

# style
sass:
  sass_dir: _sass
  style: compressed

# plugins
plugins:
  - jekyll-toc

# toc plugin
toc:
  min_level: 2
  max_level: 5

collections:
  main:
    permalink: /posts/:name/
    output: true
  sub:
    permalink: /posts/:categories/:name/
    output: true